# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
